/* GENERATED BY build.py — DO NOT EDIT.
   Edit ANCHOR_SWAP in build.py and rerun `python3 build.py`. */
window.SK_ANCHORS = {
  "chana": {
    "name": "Chana masala",
    "short": "chana",
    "mon-lunch": "Chana masala bowl",
    "thu-dinner": "Chana, jeera rice, cumin-garam tofu + chili-cumin veg",
    "batch-name": "Chana masala",
    "mon-row": "Chana masala 1½ / 2 cups · rice 1 / 1½ cups · edamame ½ / 1 cup · cilantro",
    "soak": "soak <strong>2 cups dried chickpeas</strong> for the chana",
    "mise": "Dried chickpeas (soaking)",
    "shop": "Dried chickpeas, 4 lb &mdash; 2 cups a week for the chana",
    "session": "2:45",
    "gantt": "<span class=\"bar wet\" style=\"left:10.3%; width:32.1%;\">chana</span><span class=\"bar wet\" style=\"left:45.5%; width:15.2%;\">rice</span>",
    "pot-steps": "<li><span class=\"clock\">0:17</span><span><strong>Chana.</strong> Saut&eacute; mode, 2 tbsp oil, <strong>2 tsp cumin seeds</strong> until they sizzle and darken. Then the diced onions &mdash; <strong>a full 10 minutes</strong>, until genuinely golden.</span></li><li><span class=\"clock\">0:27</span><span>Garlic and ginger, 1 min. Then <strong>2 tbsp tomato paste</strong> and the ground spices &mdash; <strong>2 tbsp coriander, 1 tbsp cumin, 2 tsp turmeric, 1&ndash;2 tsp kashmiri chili</strong> &mdash; 1 min, to bloom in the fat.</span></li><li><span class=\"clock\">0:30</span><span><strong>1 &times; 28 oz crushed tomatoes</strong>, the drained soaked chickpeas, <strong>2&frac12; cups water</strong>, <strong>2 tsp salt</strong>. Seal, 18 min high pressure, 10 min natural release. <strong>~12 min just to come to pressure</strong> &mdash; that is why it is done at 1:12.<span class=\"hands-off\">hands off &rarr; 1:12</span></span></li>",
    "pot-done": "<li><span class=\"clock\">1:12</span><span>Chana done. Mash a few chickpeas against the pot to thicken. <strong>1 tbsp garam masala</strong> and <strong>the juice of 1 lemon</strong> in <em>off the heat</em>. Spread on a pan to cool.</span></li><li><span class=\"clock\">1:15</span><span><strong>Rice, batch 1.</strong> Rinse the pot. <strong>5 cups basmati, rinsed until the water runs clear, 5 cups water</strong>, pinch of salt. 6 min high pressure, <strong>full 10 min natural release</strong>. <em>Check your Instant Pot’s half-full line &mdash; 5 cups dry is about the limit on a 6-quart.</em><span class=\"hands-off\">hands off &rarr; 1:40</span></span></li>",
    "rice-out": "<li><span class=\"clock\">1:40</span><span>Rice out. Fluff and spread on a sheet pan to cool fast.</span></li>",
    "note": ""
  },
  "rajma": {
    "name": "Rajma",
    "short": "rajma",
    "mon-lunch": "Rajma bowl",
    "thu-dinner": "Rajma, jeera rice, cumin-garam tofu + chili-cumin veg",
    "batch-name": "Rajma",
    "mon-row": "Rajma 1½ / 2 cups · rice 1 / 1½ cups · edamame ½ / 1 cup · cilantro",
    "soak": "soak <strong>2 cups dried red kidney beans</strong> for the rajma, and <strong>throw the soaking water away</strong>",
    "mise": "Dried red kidney beans (soaking)",
    "shop": "Dried red kidney beans, 4 lb &mdash; 2 cups a week for the rajma",
    "session": "3:00",
    "gantt": "<span class=\"bar wet\" style=\"left:10.3%; width:40.0%;\">rajma</span><span class=\"bar wet\" style=\"left:52.1%; width:15.2%;\">rice</span>",
    "pot-steps": "<li><span class=\"clock\">0:17</span><span><strong>Rajma.</strong> Saut&eacute; mode, 3 tbsp oil, <strong>2 tsp cumin seeds</strong> and <strong>1 tsp fenugreek</strong> until they sizzle and darken. Then the diced onions &mdash; <strong>a full 12 minutes</strong>, to genuinely brown, not just soft. <em>Rajma has less acidity to hide behind, so the onions do more of the work.</em></span></li><li><span class=\"clock\">0:29</span><span>Garlic and ginger, 1 min. Then <strong>2 tbsp tomato paste</strong> and the ground spices &mdash; <strong>2 tbsp coriander, 1 tbsp cumin, 2 tsp turmeric, 1&ndash;2 tsp kashmiri chili</strong> &mdash; 1 min, to bloom in the fat.</span></li><li><span class=\"clock\">0:31</span><span><strong>1 &times; 28 oz crushed tomatoes</strong>, the drained soaked beans, <strong>4 cups water</strong>, <strong>2 tsp salt</strong>. Seal, <strong>25 min high pressure, 15 min natural release</strong> &mdash; kidney beans want longer at both ends. <strong>~12 min just to come to pressure.</strong><span class=\"hands-off\">hands off &rarr; 1:23</span></span></li>",
    "pot-done": "<li><span class=\"clock\">1:23</span><span>Rajma done. Mash a <em>generous</em> handful of beans against the pot &mdash; rajma should sit on rice, not run off it. <strong>1 tbsp garam masala</strong> and <strong>the juice of 1 lemon</strong> in <em>off the heat</em>. Spread on a pan to cool.</span></li><li><span class=\"clock\">1:26</span><span><strong>Rice, batch 1.</strong> Rinse the pot. <strong>5 cups basmati, rinsed until the water runs clear, 5 cups water</strong>, pinch of salt. 6 min high pressure, <strong>full 10 min natural release</strong>. <em>Check your Instant Pot’s half-full line &mdash; 5 cups dry is about the limit on a 6-quart.</em><span class=\"hands-off\">hands off &rarr; 1:51</span></span></li>",
    "rice-out": "<li><span class=\"clock\">1:51</span><span>Rice out. Fluff and spread on a sheet pan to cool fast.</span></li>",
    "note": "<strong>Rajma weeks run about fifteen minutes longer.</strong> Kidney beans need 25 minutes at pressure and a full 15-minute natural release against the chana’s 18 and 10, so the pot is busy until 1:23. Everything after it &mdash; both rice batches, portioning &mdash; shifts back with it. The dry track is unaffected. <strong>Soak them and pressure-cook them:</strong> a low, gentle simmer concentrates the lectin in raw kidney beans rather than destroying it, which is why there is no stovetop fallback here."
  }
};
